version: "3.7"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: mattermost/mattermost-team-edition:7.8
    depends_on:
      - db
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10"
    ports:
      - "8065:8065"
    volumes:
      - app-data:/mattermost/data
      - app-config:/mattermost/config
    restart: unless-stopped

volumes:
  db-data:
  app-data:
  app-config: